#!/usr/bin/env python
import sys
import argparse

parser = argparse.ArgumentParser(description='Mock realmd for acceptance testing')
parser.add_argument('command', help='command - must be `join`')
parser.add_argument('domain', help='realm to join')
parser.add_argument('--computer-ou', help='Computer OU')
parser.add_argument('-U', help='username')
args = parser.parse_args()

ACCEPT_USER     ='join_user'
ACCEPT_PASSWORD = 'topsecret'
ACCEPT_REALM    = 'realm'

password = raw_input("fake password please: ")
status = 255

if args.command == "join":

    if password == ACCEPT_PASSWORD and args.U == ACCEPT_USER:
        if args.domain == ACCEPT_REALM:
            print "OK: %s" % args.computer_ou
            with open('/etc/krb5.keytab', 'w') as f:
                f.write("mock: keytab")
                status = 0

        else:
            print "bad realm"

    else:
        print "bad password! username=%s password=%s" % (args.U, password)
else:
    print "bad command for realm - want `join` got :`%s`" % args.command
sys.exit(status)